In [28]:
import torch
import pandas as pd 
import numpy as np


In [2]:
#Create tensors
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

# Vectors and Matrixes
Vectors have one dimension and matrixes have two dimensions. But, tensors have any dimensions.

# Random Tensor
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers, and then adjust those random numbers to better represent the data.


In [4]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1753, 0.7803, 0.6525, 0.7112],
        [0.0682, 0.5040, 0.9135, 0.3026],
        [0.6537, 0.2988, 0.5662, 0.5295]])

In [6]:
#Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) #height, width, color channels
random_image_tensor.ndim

3

In [7]:
#Also we can use zeros and ones tensors
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# Creating a range of tensors and tensors-like

In [12]:
range_tensor = torch.arange(0,10)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
zeros_like = torch.zeros_like(range_tensor)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

In [13]:
#float32 dtype is the default dtype of tensors.
zero = torch.zeros(size=(3,5), dtype = torch.float16)
zero

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float16)

## There are 3 common mistakes in Pytorch:

1. Tensors not right datatpye
2. Tensors not right shape
3. Tensors not on the right device

In [14]:
ones = torch.ones(size=(5,5),
                 dtype = None,
                 device = None,
                 requires_grad = False #Whether or not track gradients with this tensors operations.
                 )
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

# Tensor Operations

* Addition
* Subtraction
* Multiplication (Element Wise)
* Division
* Matrix multiplication


In [15]:
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [16]:
tensor * 3

tensor([3, 6, 9])

In [17]:
torch.mul(tensor,5)

tensor([ 5, 10, 15])

In [18]:
#Matrix Multiplication (Dot Product)
torch.matmul(tensor, tensor) #Much more efficient way than hand by matrix multiplication

tensor(14)

* The **inner dimensions** must match.
* The resulting matrix has the shape of the **outer dimensions**
* (2,3) @ (3,2) -> (2,2)

* We can use **transpose function** to switch inner and outer dimension.

In [26]:
tensor = torch.rand(3,2)
tensor

tensor([[0.4608, 0.9102],
        [0.5683, 0.4877],
        [0.0239, 0.4521]])

In [23]:
tensor.T.shape

torch.Size([2, 3])

# Finding the min, max, mean, sum
* To find **position** of min max values, use argmin(), argmax()

In [27]:
torch.min(tensor)

tensor(0.0239)

In [28]:
torch.max(tensor)

tensor(0.9102)

In [29]:
torch.mean(tensor)

tensor(0.4838)

## Reshaping, View, Stacking, Squeezing, Unsqueezing, Permute 

* Reshaping -> reshapes an input tensor to a defined shape
* View -> return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking -> combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeezing -> remove all '1' dimensions from a tensor
* Unsqueezing -> add '1' dimension to a target tensor
* Permute -> Return a view of the input with dimensions permuted (swapped) in a certain way

In [2]:
x = torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [3]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [4]:
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [5]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [8]:
#Squeezing - Remove all single dimesions from a target tensor
x_squ=x_reshaped.squeeze()
x_squ

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Unsqueezing - Add a single dimension
x_squ.unsqueeze(dim=0).shape

torch.Size([1, 9])

In [11]:
x_squ.unsqueeze(dim=1).shape

torch.Size([9, 1])

In [17]:
#Permuting - Rearrange the tensor
x_original = torch.rand(size=(224,224,3))# height, width, color channels
x_permuted = x_original.permute(2,0,1)# 0->1, 1->2, 2->0
x_permuted.shape

torch.Size([3, 224, 224])

# Indexing

It is similar to indexing with NumPy

In [18]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [19]:
x[0][0]

tensor([1, 2, 3])

In [20]:
x[0,0]

tensor([1, 2, 3])

In [21]:
x[0][0][0]

tensor(1)

In [22]:
x[0,:,1]

tensor([2, 5, 8])

In [23]:
#Tensor to NumPy array
x = x.numpy()
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int64)

# Reproducbility (Trying to take random out of random)
In short how a neural network learns:
* Start with random numbers -> Tensor operations -> Update random numbers 
* To reduce the randomness in neural networks and PyTorch comes the consept of a **random seed**. Essentially what the random seed does is "flavour" the randomness.


# Access to GPU

In [30]:
torch.cuda.is_available()

True

In [31]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [32]:
#Count number of devices
torch.cuda.device_count()

1

# Putting tensors or models on the GPU

In [36]:
#Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [37]:
# Move tensor to GPU (if available)
# If tensor is on GPU, can't transform it to NumPy!
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')